### ISSUE TITLE
Add option to make documentation on the output optional

### ISSUE THREAD

**Issue by anapaulagomes** [jllorencetti/pytest-deadfixtures#1]
First of all, nice job with the plugin! :) Really helpful. I'd like to suggest adding an option to make the doc optional. When I ran the plugin on a codebase that contains lots of fixtures, some with docs and others not, the output seems confused. Taking the docs off, the output seems cleaner. Would be nice to have this option.

What do you think?

**Comment by jllorencetti** [comment]
@anapaulagomes thx!
For some reason I didn't got notified about your issues here, but I was thinking about this too so version[ 0.2.0](https://github.com/jllorencetti/pytest-deadfixtures/releases/tag/0.2.0) have it :tada: 

README have an example.

**Comment by anapaulagomes** [comment]
Works like a charm. Awesome! 👍🏽
