### ISSUE TITLE
Plugin causes invalid output

### ISSUE THREAD

**Issue by sobolevn** [jllorencetti/pytest-deadfixtures#16]
Hi, thanks for the awesome idea. I have found several issues using this project.

But, I have faced an issue in one of my projects.

## How it is now

I am 100% sure that I don't have any duplicates or unused fixtures.
Link to tests: https://github.com/wemake-services/wemake-django-template/blob/master/tests/test_project_generation.py
That's exactly what this plugin reports. But it does report something really strange:

```
============================= test session starts ==============================
platform linux -- Python 3.6.5, pytest-3.5.1, py-1.5.3, pluggy-0.6.0
rootdir: /home/travis/build/wemake-services/wemake-django-template, inifile: setup.cfg
plugins: isort-0.1.0, flake8-1.0.0, deadfixtures-2.0.0, cookies-0.3.0
collected 16 items                                                             
Cool, every declared fixture is being used.
You may have some duplicate fixtures:
========================= no tests ran in 0.02 seconds =========================
The command "pipenv run python -m pytest" exited with 0.
```

What does it mean? Are tests executed? Why `You may have some duplicate fixtures` label is shown without any items?

Link to the build: https://travis-ci.org/wemake-services/wemake-django-template/builds/371985278

## How it should be

```
============================= test session starts ==============================
platform linux -- Python 3.6.5, pytest-3.5.1, py-1.5.3, pluggy-0.6.0
rootdir: /home/travis/build/wemake-services/wemake-django-template, inifile: setup.cfg
plugins: isort-0.1.0, flake8-1.0.0, deadfixtures-2.0.0, cookies-0.3.0
collected 16 items                                                             
Cool, every declared fixture is being used.
You don't have any duplicate fixtures.

....
========================= 4 tests ran in 0.02 seconds =========================
The command "pipenv run python -m pytest" exited with 0.
```

## Offtopic

Are you interested in creating "Projects using it" section? I would be happy to submit https://github.com/wemake-services/wemake-django-template

**Comment by jllorencetti** [comment]
Hi @sobolevn thanks for the detailed report, that seems odd indeed, I'll take a look at it later today.

That's a very cool idea! I'd add this section between `Usage` and `Contributing`.

**Comment by jllorencetti** [comment]
@sobolevn version 2.0.1 fixed the problem, thanks for reporting. :tada: 

One quick observation:
Currently the `dup-fixtures` command always return `0` as it's exit code, even when duplicated fixtures are found.
The main reason for this is that it's still in a very experimental fase, i.e. something could be falsely reported, and it'd break some builds out there.

If I may suggest you something, for now I'd recommend only using the `dead-fixtures` command in your build step, and add the `dup-fixtures` in some manually executed step, like your `Makefile`, `pre-commit` config and something like that.

**Comment by sobolevn** [comment]
Let's discuss it in a separate issue. Thanks @jllorencetti !

**Comment by sobolevn** [comment]
@jllorencetti tests count is still invalid.

Plugin version: `deadfixtures-2.0.1`
Collected: 16 tests
Run: 0
Link: https://travis-ci.org/wemake-services/wemake-django-template/jobs/372351652#L565
