### ISSUE TITLE
deadfixture doesn't support pytest-lazy-fixture

### ISSUE THREAD

**Issue by rougeth** [jllorencetti/pytest-deadfixtures#21]
The pytest-lazy-fixture plugin makes possible to use a fixtures inside `pytest.mark.parametrize`:

```python
@pytest.fixture(params=[1, 2])
def one(request):
    return request.param

@pytest.mark.parametrize('arg1,arg2', [
    ('val1', pytest.lazy_fixture('one')),
])
def test_func(arg1, arg2):
    assert arg2 in [1, 2]
```

In this example, `deadfixtures` doesn't detect the fixture `one` being used and returns the warning.

Ref: There is a proposal in Pytest to make this behaviour possible out of the box: https://docs.pytest.org/en/latest/proposals/parametrize_with_fixtures.html

**Comment by spumer** [comment]
Any updates?

**Comment by jllorencetti** [comment]
@spumer I'll take a look again at lazy fixture code, the last time I checked there was no reliable way to say that a fixture is being used, if that is the case, I'll close this with `wont-fix`.

**Comment by kazqvaizer** [comment]
I found that there is the same problem with fixtures that are only used in `pytest.mark.usefixtures` statements. They are also marked as not being used

**Comment by kazqvaizer** [comment]
> I found that there is the same problem with fixtures that are only used in `pytest.mark.usefixtures` statements. They are also marked as not being used

Sorry, my bad, this fixture was really unused. The whole file with tests was ignored because of forgotten `tests_` prefix in file name!

So this tool helps in refactoring, very nice!

**Comment by jeffersfp** [comment]
Holy moly! I'm facing this issue... What did you guys do to handle this problem?

**Comment by jllorencetti** [comment]
@jeffersfp sorry for the delay.
The way that I personally deal with it is by rewriting my tests so I don't need to use lazyfixtures.

I'm planning a rewrite of this plugin to clean up the code a bit and make the options behavior more consistent, during this it **might** be possible that this problem is solved as a *side-effect*.
However it is just a **maybe** as I don't intend to explicitly support lazy-fixtures.

So, I'm closing this as "by-design".

**Comment by anukul** [comment]
@jllorencetti Agree with your approach of rewriting to avoid certain (anti-)patterns, but it may not be possible for fixtures overriden by the user that are called dynamically / lazily by libraries.

For this use case, I request that we address #27
