### ISSUE TITLE
pytest-factoryboy support

### ISSUE THREAD

**Issue by sobolevn** [jllorencetti/pytest-deadfixtures#22]
When using `pytest-factoryboy` with the plugin I face this kind of issue:

```python
# -*- coding: utf-8 -*-

import pytest
from django.contrib.auth.models import User
from factory.django import DjangoModelFactory
from pytest_factoryboy import register


@register
class UserFactory(DjangoModelFactory):
    class Meta:
        model = User

    username = 'sobolevn'


@pytest.mark.django_db
def test_user(user):
    assert user.username == 'sobolevn'
```

And then executiing `pytest --dead-fixtures`:

```
Hey there, I believe the following fixture(s) are not being used:
Fixture name: user_factory, location: <string>:3
```

What can I do to remove this warning?

**Comment by pydolan** [comment]
Any thoughts on what's needed to resolve this?

**Comment by jllorencetti** [comment]
@pydolan I believe we need to "fine-tune" this check [1], it's possible that resolving this would improve the support for every other plugin besides `pytest-factoryboy` that automatically declares fixtures.

[1] https://github.com/jllorencetti/pytest-deadfixtures/blob/master/pytest_deadfixtures.py#L84-L89
